# Generated by Django 4.0.3 on 2022-05-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                (
                    "save_count",
                    models.IntegerField(
                        default=0, help_text="Number of times the object has been saved"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        default="LDN", max_length=3
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("line1", models.CharField(max_length=100)),
                (
                    "postcode",
                    models.CharField(
                        help_text="UK Postcode/US zip code", max_length=10
                    ),
                ),
                ("city", models.CharField(max_length=30)),
                ("county", models.CharField(blank=True, max_length=30, null=True)),
                ("notes", models.TextField(blank=True, max_length=2000, null=True)),
                ("delivery_address", models.BooleanField(default=True)),
                ("billing_address", models.BooleanField(default=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                (
                    "save_count",
                    models.IntegerField(
                        default=0, help_text="Number of times the object has been saved"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        default="LDN", max_length=3
                    ),
                ),
                ("name", models.CharField(max_length=60)),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="addresses.country",
                    ),
                ),
            ],
        ),
    ]
